import { action } from "./_generated/server";
import { api, internal } from "./_generated/api";
import { v } from "convex/values";
import { mergeTokenTemplateTextToHtml } from "./templateRender";

type GenerateLetterResult =
  | { ok: true; html: string; bulletsAutoGenerated?: boolean }
  | { ok: false; error: string };

export const generate = action({
  args: { propertyId: v.id("properties") },
  returns: v.union(
    v.object({
      ok: v.literal(true),
      html: v.string(),
      bulletsAutoGenerated: v.optional(v.boolean()),
    }),
    v.object({ ok: v.literal(false), error: v.string() }),
  ),
  handler: async (ctx, args): Promise<GenerateLetterResult> => {
    const viewer = await ctx.runQuery(api.tenancy.viewerContext, {});
    if (!viewer || viewer.role !== "admin") {
      return { ok: false, error: "Admin access is required to generate letters." };
    }
    let property = await ctx.runQuery(api.properties.get, { id: args.propertyId });
    if (!property) {
      return { ok: false, error: "Property not found." };
    }

    const useNoViolationsTemplate = property.noViolationsConfirmed === true;
    const templateVariant = useNoViolationsTemplate ? "noViolations" : "violation";

    let bulletsAutoGenerated = false;
    if (!useNoViolationsTemplate && !property.aiLetterBullets?.trim()) {
      const bulletResult = await ctx.runAction(api.inspectionBullets.generateFromInspectorNotes, {
        propertyId: args.propertyId,
      });
      if (!bulletResult.ok) {
        return { ok: false, error: bulletResult.error };
      }
      bulletsAutoGenerated = true;
      property = await ctx.runQuery(api.properties.get, { id: args.propertyId });
      if (!property) {
        return { ok: false, error: "Property not found." };
      }
    }

    const uploadedTemplate = await ctx.runQuery(api.letterTemplateDocs.getActive, {
      variant: templateVariant,
    });
    if (!uploadedTemplate) {
      return {
        ok: false,
        error: useNoViolationsTemplate
          ? "No no-violations letter template found. Upload one in Settings."
          : "No uploaded template found. Go to Settings and upload a DOCX or PDF template.",
      };
    }

    const maintenanceItemsPlain = useNoViolationsTemplate ? "" : property.aiLetterBullets?.trim() || "";
    const maintenanceItems = maintenanceItemsPlain
      .split("\n")
      .map((x) => x.replace(/^[-*•]\s*/, "").trim())
      .filter(Boolean);
    const date = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    const templateText = uploadedTemplate.templateText?.trim();
    if (!templateText) {
      return {
        ok: false,
        error: useNoViolationsTemplate
          ? "No-violations letter template has no saved text. Open Settings and save the template."
          : "Violation letter template has no saved text. Open Settings and save the template.",
      };
    }

    const html = mergeTokenTemplateTextToHtml(templateText, {
      date,
      recipientName: property.homeownerNames?.trim() || "Homeowner",
      recipientStreet: property.address,
      recipientCityStateZip: "Fairfax, VA 22030",
      maintenanceItems,
    });
    return { ok: true, html, bulletsAutoGenerated: bulletsAutoGenerated || undefined };
  },
});

export const send = action({
  args: { propertyId: v.id("properties") },
  handler: async (ctx, args): Promise<{ success: boolean; error?: string }> => {
    const viewer = await ctx.runQuery(api.tenancy.viewerContext, {});
    if (!viewer || viewer.role !== "admin") {
      return { success: false, error: "Admin access is required to send letters." };
    }
    const property = await ctx.runQuery(api.properties.get, { id: args.propertyId });
    if (!property?.email) {
      return { success: false, error: "No homeowner email on record" };
    }
    if (!property.generatedLetterHtml?.trim()) {
      return { success: false, error: "No generated letter found. Generate the letter first." };
    }
    const result = await ctx.runAction(internal.resend.sendEmail, {
      to: property.email,
      subject: `HOA Inspection Notice — ${property.address}`,
      html: property.generatedLetterHtml,
    });
    if (result.success) {
      await ctx.runMutation(internal.properties.markLetterSent, { id: args.propertyId });
    }
    return result;
  },
});
