import { action } from "./_generated/server";
import { api, internal } from "./_generated/api";
import { v } from "convex/values";
import { mergeTokenTemplateTextToHtml, mergeUploadedTemplateToHtml } from "./templateRender";

type GenerateLetterResult =
  | { ok: true; html: string; bulletsAutoGenerated?: boolean }
  | { ok: false; error: string };

export const generate = action({
  args: { propertyId: v.id("properties") },
  handler: async (ctx, args): Promise<GenerateLetterResult> => {
    const viewer = await ctx.runQuery(api.tenancy.viewerContext, {});
    if (!viewer || viewer.role !== "admin") {
      return { ok: false, error: "Admin access is required to generate letters." };
    }
    let property = await ctx.runQuery(api.properties.get, { id: args.propertyId });
    if (!property) {
      return { ok: false, error: "Property not found." };
    }

    let bulletsAutoGenerated = false;
    if (!property.aiLetterBullets?.trim()) {
      const bulletResult = await ctx.runAction(api.inspectionBullets.generateFromInspectorNotes, {
        propertyId: args.propertyId,
      });
      if (!bulletResult.ok) {
        return { ok: false, error: bulletResult.error };
      }
      bulletsAutoGenerated = true;
      property = await ctx.runQuery(api.properties.get, { id: args.propertyId });
      if (!property) {
        return { ok: false, error: "Property not found." };
      }
    }

    const uploadedTemplate =
      (await ctx.runQuery(api.letterTemplateDocs.getActive, {})) ??
      (await ctx.runQuery(api.letterTemplateDocs.list, {}))[0];
    const maintenanceItemsPlain = property.aiLetterBullets?.trim() || "";
    const maintenanceItems = maintenanceItemsPlain
      .split("\n")
      .map((x) => x.replace(/^[-*•]\s*/, "").trim())
      .filter(Boolean);
    const date = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    if (!uploadedTemplate) {
      return {
        ok: false,
        error: "No uploaded template found. Go to Settings and upload a DOCX or PDF template.",
      };
    }
    const html = uploadedTemplate.templateText?.trim()
      ? mergeTokenTemplateTextToHtml(uploadedTemplate.templateText, {
          date,
          recipientName: property.homeownerNames?.trim() || "Homeowner",
          recipientStreet: property.address,
          recipientCityStateZip: "Fairfax, VA 22030",
          maintenanceItems,
        })
      : mergeUploadedTemplateToHtml(uploadedTemplate, {
          date,
          recipientName: property.homeownerNames?.trim() || "Homeowner",
          recipientStreet: property.address,
          recipientCityStateZip: "Fairfax, VA 22030",
          maintenanceItems,
        });
    return { ok: true, html, bulletsAutoGenerated: bulletsAutoGenerated || undefined };
  },
});

export const send = action({
  args: { propertyId: v.id("properties") },
  handler: async (ctx, args): Promise<{ success: boolean; error?: string }> => {
    const viewer = await ctx.runQuery(api.tenancy.viewerContext, {});
    if (!viewer || viewer.role !== "admin") {
      return { success: false, error: "Admin access is required to send letters." };
    }
    const property = await ctx.runQuery(api.properties.get, { id: args.propertyId });
    if (!property?.email) {
      return { success: false, error: "No homeowner email on record" };
    }
    if (!property.generatedLetterHtml?.trim()) {
      return { success: false, error: "No generated letter found. Generate the letter first." };
    }
    const result = await ctx.runAction(internal.resend.sendEmail, {
      to: property.email,
      subject: `HOA Inspection Notice — ${property.address}`,
      html: property.generatedLetterHtml,
    });
    if (result.success) {
      await ctx.runMutation(internal.properties.markLetterSent, { id: args.propertyId });
    }
    return result;
  },
});
