import { useEffect, useState } from "react";
import { useAction, useMutation, useQuery } from "convex/react";
import { api } from "../../../convex/_generated/api";
import { Id } from "../../../convex/_generated/dataModel";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";

/**
 * The letter compose step: generate (or load) the AI-drafted inspection
 * letter, review it, then save the draft or send it to the homeowner.
 * letters.generate returns HTML without persisting; saving/sending persists.
 */
export function LetterComposeDialog({
  propertyId,
  propertyEmail,
  letterSentAt,
  open,
  onOpenChange,
  showToast,
}: {
  propertyId: Id<"properties">;
  propertyEmail: string | undefined;
  letterSentAt: number | undefined;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  showToast: (msg: string) => void;
}) {
  const storedLetter = useQuery(api.properties.getLetterHtml, open ? { id: propertyId } : "skip");
  const generateLetter = useAction(api.letters.generate);
  const saveGeneratedLetterHtml = useMutation(api.properties.saveGeneratedLetterHtml);
  const sendLetter = useAction(api.letters.send);

  const [html, setHtml] = useState<string | null>(null);
  const [dirty, setDirty] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [sending, setSending] = useState(false);

  // Load the saved draft when the dialog opens; a fresh generate replaces it.
  useEffect(() => {
    if (!open) {
      setHtml(null);
      setDirty(false);
      return;
    }
    if (html === null && storedLetter?.html) setHtml(storedLetter.html);
  }, [open, storedLetter?.html, html]);

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const result = await generateLetter({ propertyId });
      if (result.ok === false) {
        showToast(result.error);
        return;
      }
      setHtml(result.html);
      setDirty(true);
      showToast(
        result.bulletsAutoGenerated
          ? "Findings summarized and letter drafted"
          : "Letter drafted from the findings",
      );
    } catch {
      showToast("Failed to generate letter");
    } finally {
      setGenerating(false);
    }
  };

  const persistDraft = async (): Promise<boolean> => {
    if (!html) return false;
    try {
      await saveGeneratedLetterHtml({ id: propertyId, html });
      setDirty(false);
      return true;
    } catch {
      showToast("Could not save the letter draft");
      return false;
    }
  };

  const handleSend = async () => {
    setSending(true);
    try {
      if (dirty && !(await persistDraft())) return;
      const result = await sendLetter({ propertyId });
      if (result.success) {
        showToast("Letter sent to the homeowner");
        onOpenChange(false);
      } else {
        showToast(result.error ?? "Could not send the letter");
      }
    } finally {
      setSending(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-h-[85vh] max-w-2xl overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Inspection letter</DialogTitle>
        </DialogHeader>

        {letterSentAt && (
          <p className="rounded-lg bg-petrol-soft px-3 py-2 text-xs font-medium text-petrol">
            A letter was sent {new Date(letterSentAt).toLocaleDateString()}. Sending again emails a
            new copy.
          </p>
        )}

        {html ? (
          <div className="overflow-auto rounded-lg border p-4" dangerouslySetInnerHTML={{ __html: html }} />
        ) : (
          <p className="rounded-lg border border-dashed p-6 text-center text-sm text-ink-2">
            {storedLetter === undefined
              ? "Checking for a saved draft…"
              : "No draft yet. Generate one from the inspection findings."}
          </p>
        )}

        <DialogFooter className="flex-wrap gap-2 sm:justify-between">
          <Button variant="outline" onClick={handleGenerate} disabled={generating}>
            {generating ? "Drafting…" : html ? "Regenerate draft" : "Generate draft"}
          </Button>
          <div className="flex gap-2">
            <Button
              variant="outline"
              disabled={!html || !dirty || saving}
              onClick={async () => {
                setSaving(true);
                if (await persistDraft()) showToast("Draft saved");
                setSaving(false);
              }}
            >
              {saving ? "Saving…" : "Save draft"}
            </Button>
            <Button
              disabled={!html || sending || !propertyEmail}
              title={propertyEmail ? undefined : "Add a homeowner email first"}
              onClick={handleSend}
            >
              {sending ? "Sending…" : "Send to homeowner"}
            </Button>
          </div>
        </DialogFooter>
        {!propertyEmail && (
          <p className="text-right text-xs text-ink-2">
            No homeowner email on file — add one from the header to send.
          </p>
        )}
      </DialogContent>
    </Dialog>
  );
}
