/**
 * Collect deduped bullet lines from real-notes/*.docx and write convex/letterBulletFewShot.ts.
 *
 *   npx tsx scripts/build-letter-bullet-fewshot.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { parseRealNotesDocx } from "./realNotesDocxParse";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..");
const REAL_NOTES_DIR = path.join(REPO_ROOT, "real-notes");
const OUT_FILE = path.join(REPO_ROOT, "convex", "lib", "letterBulletFewShot.ts");

const MAX_LINES = 45;
const MIN_LEN = 10;

async function main() {
  const files = fs
    .readdirSync(REAL_NOTES_DIR)
    .filter((f) => f.endsWith(".docx") && !f.startsWith("~$"))
    .sort();

  const byKey = new Map<string, string>();

  for (const fname of files) {
    const buf = fs.readFileSync(path.join(REAL_NOTES_DIR, fname));
    const rows = await parseRealNotesDocx(buf);
    for (const r of rows) {
      for (const line of r.notesMarkdown.split("\n")) {
        const stripped = line.replace(/^-\s*/, "").trim();
        if (stripped.length < MIN_LEN) continue;
        const key = stripped.toLowerCase();
        if (!byKey.has(key)) {
          byKey.set(key, stripped.startsWith("- ") ? stripped : `- ${stripped}`);
        }
      }
    }
  }

  const lines = [...byKey.values()].slice(0, MAX_LINES);
  const block =
    "Example bullets from prior owner letters (match tone, brevity, and specificity):\n\n" +
    lines.join("\n");

  const fileContent =
    "/**\n * Auto-generated by `npx tsx scripts/build-letter-bullet-fewshot.ts`.\n * Re-run when real-notes/*.docx change.\n */\n" +
    "export const LETTER_BULLET_FEW_SHOT_BLOCK: string = " +
    JSON.stringify(block, null, 0) +
    ";\n";

  fs.writeFileSync(OUT_FILE, fileContent, "utf8");
  console.log("Wrote", OUT_FILE, "with", lines.length, "example lines from", byKey.size, "unique bullets (capped).");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
